###########
# site.url, site.title

title: 'Jekyll Bootstrap Theme'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)

## GitHub
path: /jekyll-bootstrap-theme
url:  'http://henrythemes.github.io/jekyll-bootstrap-theme'

## Local
# path: 'http://127.0.0.1:4000/'
# url:  'http://127.0.0.1:4000/'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false
